name: ci-redis

on:
  pull_request:

  push:

  schedule:
    # every day at 1:15 and 12:15 UTC
    - cron: '15 1,12 * * *'

jobs:
  tests:
    name: PHP ${{ matrix.php }}-redis-${{ matrix.redis }}

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os:
          - ubuntu-latest

        php:
          - "7.4"
          - "8.0"
          - "8.1"

        redis:
          - "5"
          - "6"
          - "7"

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Start Redis v${{ matrix.redis }}
        uses: superchargejs/redis-github-action@1.4.0
        with:
          redis-version: ${{ matrix.redis }}

      - name: Install PHP with extensions
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: curl, intl, redis
          ini-values: date.timezone='UTC'
          coverage: xdebug
          tools: pecl

      - name: Install dependencies with Composer
        run: composer install --prefer-dist --no-interaction --no-progress --optimize-autoloader

      - name: Run Redis 5 tests with PhpUnit
        if: matrix.redis == '5'
        run: vendor/bin/phpunit

      - name: Run Redis 6 tests with PhpUnit and coverage
        if: matrix.redis == '6'
        run: vendor/bin/phpunit --coverage-clover=coverage.clover
