name: ci

on:
  - pull_request
  - push

jobs:
  tests:
    name: PHP ${{ matrix.php }}-redis-5

    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest

        php:
          - "7.4"
          - "8.0"
          - "8.1"
          - "8.2"

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Start Redis v4
        uses: superchargejs/redis-github-action@1.6.0
        with:
          redis-version: 5

      - name: Install PHP with extensions
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: curl, intl, redis
          ini-values: date.timezone='UTC'
          tools: composer:v2, pecl

      - name: Install dependencies with Composer
        run: composer install --prefer-dist --no-interaction --no-progress --optimize-autoloader

      - name: Run Redis tests with PhpUnit
        run: vendor/bin/phpunit --coverage-clover=coverage.clover
